import = [
	  "~/.config/alacritty/catppuccin-macchiato.toml"
]


[font]
size = 14.0
normal = { family = "MesloLGM Nerd Font", style = "Regular"}

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },]

[window]
opacity = 0.95
blur = true

