#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#c386f1'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#ff479c'
    template = '   {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#fffb38'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#2e9599'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = '  {{ if gt .Code 0 }} {{ reason .Code }}{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'shell'
    style = 'plain'
    foreground = '#ffffff'
    background = '#0077c2'
    template = '<#0077c2,transparent></>  {{ .Name }} <transparent,#0077c2></>'

  [[blocks.segments]]
    type = 'battery'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#f36943'
    background_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#111111'
    background = '#2e9599'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'kubectl'
    style = 'diamond'
    foreground = '#000000'
    background = '#ebcc34'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  Kubernetes {{.Context}} cluster {{if .Namespace}}- {{.Namespace}} namespace{{end}} '

  [[blocks.segments]]
    type = 'az'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#9ec3f0'
    template = '  Subscription {{ .Name }} ({{ if .EnvironmentName | contains "AzureCloud" }}{{ "Global" }}{{ else }}{{ .EnvironmentName }}{{ end }}) '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#E06C75'
    template = ' ~ '
