#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'
osc99 = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#2e9599'
    leading_diamond = ''
    template = '󰐝 {{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#D51111'
    template = ' {{ path .Path .Location }} '

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = ' <transparent></> '
      home_icon = ''
      style = 'agnoster'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#c19c00'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFA300{{ end }}', '{{ if gt .Ahead 0 }}#FF7070{{ end }}', '{{ if gt .Behind 0 }}#90F090{{ end }}']
    template = '  {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'node'
    style = 'diamond'
    foreground = '#3C873A'
    background = '#303030'
    leading_diamond = ''
    trailing_diamond = ' '
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a></> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    type = 'python'
    style = 'diamond'
    foreground = '#FFE873'
    background = '#306998'
    leading_diamond = ''
    trailing_diamond = ' '
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'

  [[blocks.segments]]
    type = 'go'
    style = 'diamond'
    foreground = '#06aad5'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = ' '
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#fff'
    background = '#2e9599'
    background_templates = ['{{ if gt .Code 0 }}#D51111{{ end }}']
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '_2, 15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FFF'
    foreground_templates = ['{{ if gt .Code 0 }}#D51111{{ end }}']
    template = '  '
